version: '3.1'
services:
  meteo-api:
    build:
      context: ./meteoApi
      dockerfile: Dockerfile

    hostname: meteoapi
    container_name: meteoapi

    restart: on-failure:1


    
##HOST_PORT:CONTAINER_PORT
    ports:
      - 9999:9999
      
    networks:
      - otus
    environment:
      AUTH: null

  meteo-helpers:
    build:
      context: ./meteoHelpers
      dockerfile: Dockerfile

    hostname: meteohelpers
    container_name: meteohelpers

    restart: on-failure:1


    
##HOST_PORT:CONTAINER_PORT
    ports:
      - 9998:9998
      
    networks:
      - otus
    environment:
      AUTH: null


  meteo-information:
    build:
      context: ./meteoInformation
      dockerfile: Dockerfile

    hostname: meteoinformation
    container_name: meteoinformation

    restart: on-failure:1


    
##HOST_PORT:CONTAINER_PORT
    ports:
      - 9997:9997
      
    networks:
      - otus
    environment:
      AUTH: null


  meteo-producers:
    build:
      context: ./meteoProducers
      dockerfile: Dockerfile

    hostname: meteoproducers
    container_name: meteoproducers

    restart: on-failure:1


    
##HOST_PORT:CONTAINER_PORT
    ports:
      - 9996:9996
      
    networks:
      - otus
    environment:
      AUTH: null

  meteo-services:
    build:
      context: ./meteoServices
      dockerfile: Dockerfile

    hostname: meteoservices
    container_name: meteoservices

    restart: on-failure:1


    
##HOST_PORT:CONTAINER_PORT
    ports:
      - 9995:9995
      
    networks:
      - otus
    environment:
      AUTH: null


  meteo-users:
    build:
      context: ./meteoUsers
      dockerfile: Dockerfile

    hostname: meteousers
    container_name: meteousers

    restart: on-failure:1


    
##HOST_PORT:CONTAINER_PORT
    ports:
      - 9994:9994
      
    networks:
      - otus
    environment:
      AUTH: null


 

  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    networks:
      -  otus

    hostname: zipkin

  prometheus:
    image: prom/prometheus
#    depends_on:
#      - meteo-api
    container_name: prometheus
    ports:
      - 9090:9090
    networks:
      - otus
    volumes:
      - ./monitoring/prometheus/:/etc/prometheus/
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    restart: on-failure:1
    hostname: prometheus

  grafana:
    image: grafana/grafana
#    depends_on:
#      - prometheus
    ports:
      - 3000:3000
    volumes:
      - ./monitoring/grafana/:/etc/grafana/provisioning/
    env_file:
      - ./monitoring/grafana/config.monitoring
    networks:
      - otus
    restart: on-failure:1
    hostname: grafana


####include gafana LOKI
  grafana-loki:
    image: grafana/loki
    ports:
      - 3100:3100    
    
    networks:
      - otus
    restart: on-failure:1
    hostname: loki

networks:
  otus:
    driver: bridge

   
networks:
  otus:
    driver: bridge
