version: '3.1'
services:

  meteo-api:
    build:
      context: ./meteoApi
      dockerfile: Dockerfile
    hostname: meteoapi
    container_name: meteoapi
    restart: on-failure:1
    
##HOST_PORT:CONTAINER_PORT
    ports:
      - 8080:9999
      
    networks:
      - otus

    environment:
      AUTH: null

networks:
  otus:
    driver: bridge
