- job_name: 'meteoapi-job-2'
  scrape_interval: 15s
  #scrape_timeout: 10s
  #evaluation_interval: 15s
  metrics_path: '/actuator/prometheus'
  static_configs:
   - targets: ['10.1.1.90:9999']

- job_name: 'meteohelpers-job-2'
  scrape_interval: 15s
  #scrape_timeout: 10s
  #evaluation_interval: 15s
  metrics_path: '/actuator/prometheus'
  static_configs:
   - targets: ['10.1.1.90:9998']

- job_name: 'meteoinformation-job-2'
  scrape_interval: 15s
  #scrape_timeout: 10s
  #evaluation_interval: 15s
  metrics_path: '/actuator/prometheus'
  static_configs:
   - targets: ['10.1.1.90:9997']

- job_name: 'meteoproducers-job-2'
  scrape_interval: 15s
  #scrape_timeout: 10s
  #evaluation_interval: 15s
  metrics_path: '/actuator/prometheus'
  static_configs:
   - targets: ['10.1.1.90:9996']

- job_name: 'meteoservices-job-2'
  scrape_interval: 15s
  #scrape_timeout: 10s
  #evaluation_interval: 15s
  metrics_path: '/actuator/prometheus'
  static_configs:
   - targets: ['10.1.1.90:9995']


- job_name: 'meteousers-job-2'
  scrape_interval: 15s
  #scrape_timeout: 10s
  #evaluation_interval: 15s
  metrics_path: '/actuator/prometheus'
  static_configs:
   - targets: ['10.1.1.90:9994']



#- job_name: 'sample-pods'
#  scrape_interval: 1s
#  metrics_path: /
#  kubernetes_sd_configs:
#    - role: endpoints
  #- job_name: 'meteoInformation-job'
  #  metrics_path: '/actuator/prometheus'
  #  static_configs:
  #    - targets: ['meteoInformation:8081']
  #- job_name: 'meteoProducers-job'
  #  metrics_path: '/actuator/prometheus'
  #  static_configs:
  #    - targets: ['meteoProducers:8082']