global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'meteoApi-job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['meteoApi:8080']
- job_name: 'meteoInformation-job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['meteoInformation:8081']
- job_name: 'meteoProducers-job'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['meteoProducers:8082']