appname: meteo-api
replicas: 1
image:
  repository: localhost:5000/meteo-api
  pullPolicy: Always
 # Overrides the image tag whose default is the chart appVersion.
  tag: latest
livenessProbe:
  httpGet:  
    path: /actuator/health
    port: 9999
  initialDelaySeconds: 5
readinessProbe:
  httpGet:
    path: /actuator/health
    port: 9999
  initialDelaySeconds: 5
  

deployment:
  ports:
    - name: http
      containerPort: 9999
      protocol: TCP
  
  
service:
  type: ClusterIP
  ports:
    port: 30001
    targetPort: http
  




##########
#appname: meteo-api
#image:
#  repository: moryakovdv/meteo-api
#  tag: 0.0.1
#  pullPolicy: Always

#replicaCount: 1
#resources:
#  limits:
#    cpu: 1000m
#    memory: 512Mi

#ports:
#  name: http
#  containerPort: 9999
#  protocol: TCP
#  targetPort: 9999
#  appProtocol: http

#service:
#  type: ClusterIP
#  port: 9999



###########

#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: meteo-api
#  namespace: default
#spec:
#  replicas: 1
#  selector:
#    matchLabels:
#      meteo-api: web
#  template:
#    metadata:
#      labels:
#        meteo-api: web
#    spec:
#      containers:
#        - name: meteo-api
#          image: moryakovdv/meteo-api
#          imagePullPolicy: Always
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: meteo-api
#  namespace: default
#spec:
#  type: NodePort
#  selector:
#    meteo-api: web
#  ports:
#    - port: 9999
#      targetPort: 9999
#      nodePort: 30001
##########